[Addon]
Name=Rime 词库配置同步
Version=5.1.19
Comment=Rime user dictionary WebDAV multi-device sync
Comment[zh_CN]=通过 WebDAV 多端同步
Type=SharedLibrary
Library=libfcitx-rime-webdav
Category=Module
OnDemand=False
Configurable=True

[Addon/Dependencies]
0=core:5.1.19
1=rime
